### ISSUE TITLE
Digital Modes and other features

### ISSUE THREAD

**Issue by jslatten** [F4HTB/Universal_HamRadio_Remote_HTML5#14]
Awesome project F4HTB! Have you looked into whether you can use some of the digital mode clients like WSJT-X or FLDIGI with this remote setup or even developing digital encoding/decoding as part of the web client & backend? 

While I'm not a developer by trade, and I'm not sure if I'm up to the task, are you open to receiving PRs for additional features, and documentation?

**Comment by F4HTB** [comment]
Hello dear jslatten,

I thought about whether it would be wise or not to put the possibility of using digital modes.
After consulting other OM friends, it actually seems not.
The most consistent remote use is to use a remote control interface and install the software on the PI directly.
I had as a project to make a complete image with a vnc via web page, perhaps on the basis of the "Guacamole" project ....

Of course I am open to all development proposals but to remain effective, it is necessary to be robust and simple.

The next version will have an additional watterfall if the script detects the insertion of an RTL key. (Already in preparation.)

For now I'm waiting to have a used 818 and install all of this in a 19 "rack to have a real development platform.

If you want to participate, I would be happy to. But don't do your work for nothing, in the sense of not doing too much superfluous duties.
Also, it goes without saying that if you do something, you have to do it properly, even if you are not a professional.

If you are interested, I try to add:
-a noise canceler in python on the rpi or javascript side like the dsp that we find for 817 but in software.
- make the complete images so that simple users will only have to burn the image on the card (I have more or less the procedure already).
-Add a function in the Configuration menu to regenerate or upload to replace the default certificates.
-Check or review the CSS so that it adapts correctly to the size of the windows.
-A javascript function for decoding the CW.
-A function to send text and have it transcribed to CW and transmit it.

I will add a todo list on the readme. :)

73 F4HTB.
